app = "arxiv-tml"
primary_region = "hkg"

[http_service]
  internal_port = 4174
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  NODE_ENV = "production"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"